[workspace]
members = ["src-tauri", "src-tauri/packages/interceptor"]
resolver = "2"

[workspace.lints.clippy]
uninlined_format_args = "allow"
new-without-default = "allow"

[profile.release]
lto = "thin"
codegen-units = 1
